

trigger:
- none

environment:
        name: Test
        resourceType: VirtualMachine
        tags: VM0
 strategy:
        runOnce:
          deploy:
            steps:
             - task: SSISCatalog@0
              displayName: SSIS Catalog Configuration
              inputs:
                configSource: 'inline'
                configContent: |
                  {
                    "folders": [
                      {
                        "name": "MIS",
                        "description": ""}]
                        }
                         rollBackOnError: true
                targetServer: 'localhost'
                authType: 'win'
                        

