#azure-pipelines.yml

trigger:
- none



stages:
  - stage: Build
    displayName: Build

    jobs:
    - deployment: DeploySSIS
      displayName: Deploy SSIS Package
      workspace:
        clean: all
      environment:
        name: VM2
        resourceType: VirtualMachine
        
      strategy:
        runOnce:
          deploy:
            steps:
            - task: SSISCatalog@0
              displayName: SSIS Catalog Configuration
              inputs:
                configSource: 'inline'
                configContent: |
                  {
                    "folders": [
                      {
                        "name": "MIS",
                        "description": "",
                        "projects": [
                          {
                            "name": "OracleToSQL",
                            "parameters": [
                              {
                                  "name": "ExponentHRMIS_ServerName",
                                  "container": "OracleToSQL",
                                  "value": "ExponentHRMIS_ServerName",
                                  "valueType": "referenced"
                              },
                              {
                                  "name": "MasterTax_ServerName",
                                  "container": "OracleToSQL",
                                  "value": "MasterTax_ServerName",
                                  "valueType": "referenced"
                              },
                              {
                                  "name": "MasterTax_UserName",
                                  "container": "OracleToSQL",
                                  "value": "MasterTax_UserName",
                                  "valueType": "referenced"
                              },
                              {
                                  "name": "MasterTax_Password",
                                  "container": "OracleToSQL",
                                  "value": "MasterTax_Password",
                                  "valueType": "referenced"
                              },
                              {
                                  "name": "MISMasterTax_ServerName",
                                  "container": "OracleToSQL",
                                  "value": "MISMasterTax_ServerName",
                                  "valueType": "referenced"
                              }
                            ],
                            "references": [
                              {
                                "environmentName": "$(SSISEnvironment)",
                                "environmentFolder": "."
                              }
                            ]
                          }
                        ],
                        "environments": [
                          {
                            "name": "$(SSISEnvironment)",
                            "description": "",
                            "variables": [
                              {
                                  "name": "ExponentHRMIS_ServerName",
                                  "type": "string",
                                  "description": "",
                                  "value": "$(ExponentHRMIS_ServerName)",
                                  "sensitive": false
                              },
                              {
                                  "name": "MasterTax_ServerName",
                                  "type": "string",
                                  "description": "",
                                  "value": "$(MasterTax_ServerName)",
                                  "sensitive": false
                              },
                              {
                                  "name": "MasterTax_UserName",
                                  "type": "string",
                                  "description": "",
                                  "value": "$(MasterTax_UserName)",
                                  "sensitive": false
                              },
                              {
                                  "name": "MasterTax_Password",
                                  "type": "string",
                                  "description": "",
                                  "value": "$(MasterTax_Password)",
                                  "sensitive": true
                              },
                              {
                                  "name": "MISMasterTax_ServerName",
                                  "type": "string",
                                  "description": "",
                                  "value": "$(MISMasterTax_ServerName)",
                                  "sensitive": false
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                rollBackOnError: true
                targetServer: 'MSSQLSERVER'
                authType: 'win'
            
